spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_sample
    username: root
    password: wangxianglu
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  context-path: /uaa
  port: 5000
logging:
  level:
    org.springframework:
      security: DEBUG
